config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :line_items
  resources :carts
  get 'carts/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  devise_for :users
  get 'shops/index'
  get 'shops/show'

  root 'home#index'

  resources :books

  namespace :charts do
    get "best-reviews"
  end
 

  resources :shops, only: [:index, :show]
  resources :order_items
  resource :carts, only:[:show]
  
  #match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
  #devise_for :users, :controllers => { :sessions => "users/sessions" }

  get 'home/index'
  get 'home/productdetail'
  get 'home/product'
  get 'home/chart'
  get 'home/contact'
  get 'home/stories'
  get 'line_items/create'
  
  
  get 'orders/checkout'



  get 'admin/index'
  get 'home/profile'

  get '/books'=> 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   # has_many :order_items
    has_many :line_items

    before_destroy :ensure_not_referenced_by_any_line_item

    private
    #Ensure that there are no line items referencing the product
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
        throw :abort
        end
    end
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, dependent: :destroy

    def add_book(book)
        current_item = line_items.find_by(book_id: book.id)
        if current_item
            current_item.quantity +=1
        else
            current_item = line_items.build(book_id: book.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum {|item| item.total_price }
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :book, optional: true
  belongs_to :cart


  def total_price
    book.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    enum pay_type: {
        "Check" => 0,
        "Credit card" => 1,
        "Purchase order" => 2
    }


    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :book

    def unit_price
        if persisted?
            self[:unit_price]
        else
            book.price
        end
    end
    
    def total
        unit_price * quantity
    end

    private
    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts
    has_many :orders
    
    def username
        return self.email.split('@')[0].capitalize
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        @books = Book.all
        @users = User.all
    end
    
    def show
        @books = Book.find(params[:id])
        @users = User.all
    end

    def new
        @book = Book.new
    end

    def edit
    end

    # CREATE /books/
    def bookcreate
        @book = Book.new(book_params)
    
        respond_to do |format|
          if @book.save
            format.html { redirect_to @book, notice: 'Book was successfully created.' }
            format.json { render :show, status: :created, location: @book }
          else
            format.html { render :new }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
      end

      # UPDATE /books/
      def bookupdate
        respond_to do |format|
          if @book.update(book_params)
            format.html { redirect_to @book, notice: 'Book was successfully updated.' }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
      end

    # DELETE /books/1
    # DELETE /books/1.json
    def bookdestroy
        @book.destroy
        respond_to do |format|
            format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @books = Book.all
    @product = Book.order("RANDOM()").limit(16);

    @product.each do |book| 
    end
end

def product
    @books = Book.all
    @product = Book.order("RANDOM()").limit(16);

    @product.each do |book| 
        
    end
end

def productdetail
    @books = Book.all
    bookselected = params[:BookSelected]
    puts "................................"
    puts bookselected 
    @selectedbook = Book.where('book_id = ?', bookselected)
    @isbn = []
    @selectedbook.each do |book|    
        @isbn << book.isbn 
    end

end

def _productdetail
    @books = Book.all
    bookselected = params[:BookSelected]
    puts "................................"
    puts bookselected 
    @selectedbook = Book.where('book_id = ?', bookselected)
    @isbn = []
    @selectedbook.each do |book|    
        @isbn << book.isbn
    end
end


def profile
end


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
include CurrentCart
before_action :set_cart
  include Pagy::Backend
  
  def index
    @books = Book.order(:title)
    @pagy, @books = pagy(Book.all, items: 10)
    search = params[:search]
    @books_search = Book.where('title like ?', "%#{search}%")
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend


    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/draft.html.erb
<% @books.each do |book| %>
<% if notice %>
<aside id="notice"><%= notice %></aside>
<% end %>
	<h1> Catalog</h1>
  <ul class = "catalog">
    <% cache @books do %>
     
        <li>
        <%= image_tag("http://covers.openlibrary.org/b/isbn/#{book.isbn}-L.jpg") %>

        <h2><%= book.title %></h2>
        <p>

        <p>
        <div class="price">
        <%= book.price %>
        <div>
        </li>
      <% end%>
    <% end %>
    </ul>

app/views/shops/index.html.erb
	<!-- Title page -->
  <!--Image from https://wallpaperaccess.com/full/253332.jpg-->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url(<%= asset_path 'about.jpg' %>);">
		<h2 class="ltext-105 cl0 txt-center">
			Shop
		</h2>
	</section>	

	<!-- Content page -->
	<section class="bg0 p-t-62">
		<div class="container ">
			<div class="row">
				<div class="col-md-8 col-lg-12">
				
						<!-- item blog -->
								<h4 class="p-b-15">
									<a href="#" class="ltext-108 cl2 hov-cl1 trans-04">
										Shop with us
									</a>
								</h4>

								<p class="stext-117 cl6">
									Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce eget dictum tortor. Donec dictum vitae sapien eu varius
								</p>

<!-- Search form -->

<style> 
input[type=text] {
  width: 130px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  font-size: 16px;
  background-color: white;
  background-image: url('searchicon.png');
  background-position: 10px 10px; 
  background-repeat: no-repeat;
  padding: 12px 20px 12px 40px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
  display: block;
}

input[type=text]:focus {
  width: 100%;
}

.cart {
  font-size: 1.414em;
}

  input[type="submit"] {
    background-color: #282;
    border-radius: 0.354em;
    border: solid thin #141;
    color: white;
    font-size: 1em;
    padding: o.354em 1em;
  }

  input[type="submit"]:hover {
    background-color: #141;
  }


</style>
           <form> 
          <%= form_tag shops_path, :method => 'get' do %>
              <%= content_tag :label do %>
                Search for a book:
                <input type="text" name="search" placeholder="Search.."<%= text_field_tag :search, params[:search] %>
                <button type="button" class="btn btn-outline-dark" style="display: block"<%= submit_tag("Search") %>Search</button>
              <% end %>
            <% end %>
         </form>
            <!--Book table section-->
            <h1 class="txt-center">Books on the shelf:</h1>
            <table id="dttb" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Book Title</th>
                  <th>Author</th>
                  <th>Average rating</th>
                  <th>Price</th>
				          <th>Image</th>
                  <th>Details</th>
                 <!-- <th>Quantity</th>-->
                  <th>Add to Cart</th>
                  <% if user_signed_in? %>
                  <% if current_user.admin == true %>
                  <th>Edit</th>
                  <th>Destroy</th>
                  <% end %>
                  <% end %>
                </tr>
              </thead>
              <tbody>
              <% cache @books do %>
              <% @books.each do |book| %>
              <% cache book do %>
			       
                <tr>
                  <td><%= book.title %></td>
                  <td><%= book.author %></td>
                  <td><%= book.avg_rating %>/5</td>
                  <td>£<%= book.price %></td>
				          <td><%= image_tag("http://covers.openlibrary.org/b/isbn/#{book.isbn}-S.jpg") %></td>

                  
                  <td><button type="button" class="btn btn-outline-info"><%= link_to 'Show', book %></button></td>
                  
                  <td><%= button_to "Add To Cart".html_safe, line_items_path(book_id: book), remote: true, class: "btn btn-outline-success" %></td>

                  
                   <% if user_signed_in? %>
                   <% if current_user.admin == true %>
                    <td><button type="button" class="btn btn-outline-dark"><%= link_to 'Edit', edit_book_path(book) %></button></td>
                    <td><button type="button" class="btn btn-outline-danger"><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
                  <% end %>
                  <% end %>
                  <% end %>
                  <% end %>
                </tr>
              <% end %> 
              </tbody>
            </table>
            <br>
            <div align="center">
                <%== pagy_nav(@pagy) %>
                <% if user_signed_in? %>
                <% if current_user.admin == true %>
                <!--<button type="button" class="btn btn-info" <%= link_to 'New Book', new_book_path %></button> -->
                <% end %>
                <% end %>
                <br>
          
            </div>
        </div>
      </div>
    </div>
  </section>
        <br>





                                                                                                                                                     

app/views/shops/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Book:</strong>
  <%= @book.book_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Avg rating:</strong>
  <%= @book.avg_rating %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Language code:</strong>
  <%= @book.language_code %>
</p>

<p>
  <strong>Num page:</strong>
  <%= @book.num_page %>
</p>

<p>
  <strong>Rating count:</strong>
  <%= @book.rating_count %>
</p>

<p>
  <strong>Text review count:</strong>
  <%= @book.text_review_count %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Back', root_path %>