config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :line_items
  resources :carts
  get 'carts/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  devise_for :users
  get 'shops/index'
  get 'shops/show'

  root 'home#index'

  resources :books

  namespace :charts do
    get "best-reviews"
  end
 

  resources :shops, only: [:index, :show]
  resources :order_items
  resource :carts, only:[:show]
  
  #match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
  #devise_for :users, :controllers => { :sessions => "users/sessions" }

  get 'home/index'
  get 'home/productdetail'
  get 'home/product'
  get 'home/chart'
  get 'home/contact'
  get 'home/stories'
  get 'line_items/create'
  
  
  get 'orders/checkout'



  get 'admin/index'
  get 'home/profile'

  get '/books'=> 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/book.rb
class Book < ApplicationRecord
   # has_many :order_items
    has_many :line_items

    before_destroy :ensure_not_referenced_by_any_line_item

    private
    #Ensure that there are no line items referencing the product
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
        throw :abort
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  include Pagy::Backend

  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json




   def index
    def index
      @pagy, @books = pagy(Book.all, items: 10)
        search = params[:search]
        @book_search = Book.where('title like ?', "%#{search}%")
        end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @books = Book.find(params[:id])
  end



  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_id, :title, :author, :avg_rating, :isbn, :language_code, :num_page, :rating_count, :text_review_count, :price)
    end
end

#class BookCover

  #include HTTPparty
  # Searching The chosen API with the following link
  #base_uri "covers.openlibrary.org/b/isbn/"

  #def posts
   # self.class.get('/posts.json')
  #end
#end

# Create a variable and a new instance of the class:
#book_cover = BookCover.new
# to call the method:
#puts book_cover.posts

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_area :author %>
  </div>

  <div class="field">
    <%= form.label :avg_rating %>
    <%= form.text_field :avg_rating %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="field">
    <%= form.label :language_code %>
    <%= form.text_field :language_code %>
  </div>

  <div class="field">
    <%= form.label :num_page %>
    <%= form.number_field :num_page %>
  </div>

  <div class="field">
    <%= form.label :rating_count %>
    <%= form.number_field :rating_count %>
  </div>

  <div class="field">
    <%= form.label :text_review_count %>
    <%= form.number_field :text_review_count %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

	<!-- Title page -->
  <!--Image from https://wallpaperaccess.com/full/253332.jpg-->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url(<%= asset_path 'about.jpg' %>);">
		<h2 class="ltext-105 cl0 txt-center">
			About
		</h2>
	</section>	


<style> 
input[type=text] {
  width: 130px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  font-size: 16px;
  background-color: white;
  background-image: url('searchicon.png');
  background-position: 10px 10px; 
  background-repeat: no-repeat;
  padding: 12px 20px 12px 40px;
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
  display: block;
}

input[type=text]:focus {
  width: 100%;
}

.cart {
  font-size: 1.414em;
}

  input[type="submit"] {
    background-color: #282;
    border-radius: 0.354em;
    border: solid thin #141;
    color: white;
    font-size: 1em;
    padding: o.354em 1em;
  }

  input[type="submit"]:hover {
    background-color: #141;
  }


</style>


	<!-- Content page -->
	<section class="bg0 p-t-62">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-12">
					<div class="p-r-45 p-r-0-lg">
						<!-- item blog -->
						<div class="p-b-63">
							<div class="p-t-32">
								<h4 class="p-b-15">
									<a href="blog-detail.html" class="ltext-108 cl2 hov-cl1 trans-04">
										About Us
									</a>
								</h4>

								<p class="stext-117 cl6">
                Here you can find the detailed infromation about our books and the statistics regarding our collection. As you may see in the charts below, the most prevalent is righly rated literature in English.								</p>
							</div>
               <form> 
          <%= form_tag shops_path, :method => 'get' do %>
              <%= content_tag :label do %>
                Search for a book:
                <input type="text" name="search" placeholder="Search.."<%= text_field_tag :search, params[:search] %>
                <button type="button" class="btn btn-outline-dark" style="display: block"<%= submit_tag("Search") %>Search</button>
              <% end %>
            <% end %>
         </form>
						</div>
            <!--Book table section-->
            
            
            <h1 class="txt-center">Books on the shelf:</h1>
            <table id="dttb" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Book Title</th>
                  <th>Author</th>
                  <th>Average rating</th>
                  <th>Isbn</th>
                  <th>Language code</th>
                  <th>Number of pages</th>
                  <th>People Rated</th>
                  <th>People Reviewed</th>
                  <th>Price</th>
                  <th>Image</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
              
             
              <% @books.each do |book| %>
              
                <tr>
                  <td><%= book.title %></td>
                  <td><%= book.author %></td>
                  <td><%= book.avg_rating %>/5</td>
                  <td><%= book.isbn %></td>
                  <td><%= book.language_code %></td>
                  <td><%= book.num_page %></td>
                  <td><%= book.rating_count %></td>
                  <td><%= book.text_review_count %></td>
                  <td>£<%= book.price %></td>
                  <td><%= image_tag("http://covers.openlibrary.org/b/isbn/#{book.isbn}-S.jpg") %></td>
                  <td><button type="button" class="btn btn-outline-info"><%= link_to 'Show', book %></button></td>
                <% if user_signed_in? %>
                <% if current_user.admin == true %>
                  <td><button type="button" class="btn btn-outline-dark"><%= link_to 'Edit', edit_book_path(book) %></button></td>
                  <td><button type="button" class="btn btn-outline-danger"><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
                <% end %>
                <% end %>
               
          
                </tr>
              <% end %>
              </tbody>
            </table>
            <br>
            <div align="center">
             <%== pagy_nav(@pagy) %>

                <% if user_signed_in? %>
                <% if current_user.admin == TRUE %>
                <button type="button" class="btn btn-info" <%= link_to 'New Book', new_book_path %></button>
                <% end %>
                <% end %>
                
            </div>
            <br>

            <div class="row">

            <div class="col-xl-8 col-lg-7">

              <!-- Area Chart -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">The amount of books by raiting</h6>
                </div>
                <div class="card-body">
                  <div class="chart-area">
                    <%= bar_chart Book.group(:avg_rating).count %>
                  </div>
                  <hr>
                </div>
              </div>
              <!-- Bar Chart -->
            </div>
            <!-- Donut Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Language code statistics</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-pie pt-4">
                   <%= pie_chart Book.group(:language_code).count %>        
                  </div>
                  <hr>    
                </div>
              </div>
            </div>
          </div>
        </div>
          </div>
				</div>
			</div>
		</div>
	</section>





  <!--<%= bar_chart @rating%>-->





 

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book ID:</strong>
  <%= @book.book_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Avg rating:</strong>
  <%= @book.avg_rating %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Language code:</strong>
  <%= @book.language_code %>
</p>

<p>
  <strong>Num page:</strong>
  <%= @book.num_page %>
</p>

<p>
  <strong>Rating count:</strong>
  <%= @book.rating_count %>
</p>

<p>
  <strong>Text review count:</strong>
  <%= @book.text_review_count %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>