config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :line_items
  resources :carts
  get 'carts/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  devise_for :users
  get 'shops/index'
  get 'shops/show'

  root 'home#index'

  resources :books

  namespace :charts do
    get "best-reviews"
  end
 

  resources :shops, only: [:index, :show]
  resources :order_items
  resource :carts, only:[:show]
  
  #match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
  #devise_for :users, :controllers => { :sessions => "users/sessions" }

  get 'home/index'
  get 'home/productdetail'
  get 'home/product'
  get 'home/chart'
  get 'home/contact'
  get 'home/stories'
  get 'line_items/create'
  
  
  get 'orders/checkout'



  get 'admin/index'
  get 'home/profile'

  get '/books'=> 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   # has_many :order_items
    has_many :line_items

    before_destroy :ensure_not_referenced_by_any_line_item

    private
    #Ensure that there are no line items referencing the product
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
        throw :abort
        end
    end
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, dependent: :destroy

    def add_book(book)
        current_item = line_items.find_by(book_id: book.id)
        if current_item
            current_item.quantity +=1
        else
            current_item = line_items.build(book_id: book.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum {|item| item.total_price }
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :book, optional: true
  belongs_to :cart


  def total_price
    book.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    enum pay_type: {
        "Check" => 0,
        "Credit card" => 1,
        "Purchase order" => 2
    }


    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :book

    def unit_price
        if persisted?
            self[:unit_price]
        else
            book.price
        end
    end
    
    def total
        unit_price * quantity
    end

    private
    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts
    has_many :orders
    
    def username
        return self.email.split('@')[0].capitalize
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @books = Book.all
    @product = Book.order("RANDOM()").limit(16);

    @product.each do |book| 
    end
end

def product
    @books = Book.all
    @product = Book.order("RANDOM()").limit(16);

    @product.each do |book| 
        
    end
end

def productdetail
    @books = Book.all
    bookselected = params[:BookSelected]
    puts "................................"
    puts bookselected 
    @selectedbook = Book.where('book_id = ?', bookselected)
    @isbn = []
    @selectedbook.each do |book|    
        @isbn << book.isbn 
    end

end

def _productdetail
    @books = Book.all
    bookselected = params[:BookSelected]
    puts "................................"
    puts bookselected 
    @selectedbook = Book.where('book_id = ?', bookselected)
    @isbn = []
    @selectedbook.each do |book|    
        @isbn << book.isbn
    end
end


def profile
end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend


    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admin_old/index.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: "partials/banner", locals: { banner: @banner } %>



<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Title</th>
      <th>Author</th>
      <th>Avg rating</th>
      <th>Isbn</th>
      <th>Language code</th>
      <th>Num page</th>
      <th>Rating count</th>
      <th>Text review count</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>

      <tr>

        <td><%= book.book_id %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.avg_rating %></td>
        <td><%= book.isbn %></td>
        <td><%= book.language_code %></td>
        <td><%= book.num_page %></td>
        <td><%= book.rating_count %></td>
        <td><%= book.text_review_count %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bookshelf Home</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



	<!--<link rel="stylesheet" href="app/assets/stylesheets/util.css.scss">-->
	<!--<link rel="stylesheet" href="app/assets/stylesheets/main.css.scss">-->
<!--===============================================================================================-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<link href="https://fonts.googleapis.com/css?family=Yesteryear&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

  <%= stylesheet_link_tag "util" %>
  <%= stylesheet_link_tag "main" %>  

<!--<link rel="icon" type="image/png" href="/images/icons/favicon.png"/>-->	

<!--<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="fonts/linearicons-v1.0.0/icon-font.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">-->

<!--<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">-->	

<!--<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">-->	
	
<!--<link rel="stylesheet" type="text/css" href="vendor/slick/slick.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="vendor/MagnificPopup/magnific-popup.css">-->
	
<!--<link rel="stylesheet" type="text/css" href="vendor/perfect-scrollbar/perfect-scrollbar.css">-->
	




<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>




</head>
  <body class="animsition">






    <%= render partial: "partials/header", locals: { header: @header } %>
    <%= yield %>
    <%= render partial: "partials/footer", locals: { footer: @footer } %>


    

 <!--===============================================================================================-->	
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/slick/slick.min.js"></script>
	<script src="javascript/slick-custom.js"></script>
<!--===============================================================================================-->
	<script src="vendor/parallax100/parallax100.js"></script>
	<script>
        $('.parallax100').parallax100();
	</script>
<!--===============================================================================================-->
	<script src="vendor/MagnificPopup/jquery.magnific-popup.min.js"></script>
	<script>
		$('.gallery-lb').each(function() { // the containers for all your galleries
			$(this).magnificPopup({
		        delegate: 'a', // the selector for gallery item
		        type: 'image',
		        gallery: {
		        	enabled:true
		        },
		        mainClass: 'mfp-fade'
		    });
		});
	</script>
<!--===============================================================================================-->
	<script src="vendor/isotope/isotope.pkgd.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/sweetalert/sweetalert.min.js"></script>
	<script>
		$('.js-addwish-b2').on('click', function(e){
			e.preventDefault();
		});

		$('.js-addwish-b2').each(function(){
			var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-b2');
				$(this).off('click');
			});
		});

		$('.js-addwish-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-detail');
				$(this).off('click');
			});
		});

		/*---------------------------------------------*/

		$('.js-addcart-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});
	
	</script>
<!--===============================================================================================-->
	<script src="vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
	<script>
		$('.js-pscroll').each(function(){
			$(this).css('position','relative');
			$(this).css('overflow','hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function(){
				ps.update();
			})
		});
	</script>
<!--===============================================================================================-->
	<!--<script src="javascript/main.js"></script> -->

  <%= javascript_tag "main" %>
  <%= javascript_tag "map-custom" %>
  <%= javascript_tag "slick-custom" %>


  </body>

<!--This was an attempt to resolve an issue of links (pages need to be reloaded manually)-->
  <!--<script type="text/javascript">
//https://stackoverflow.com/questions/6160415/reload-an-html-page-just-once-using-javascript
   if(window.location.href.substr(-2) !== "?r") {
      window.location = window.location.href + "?r";
    }
</script> -->
</html>

app/views/partials/_cartselectors.html.erb
<div class="p-t-33">
							<div class="flex-w flex-r-m p-b-10">
								<div class="size-203 flex-c-m respon6">
									Type
								</div>

								<div class="size-204 respon6-next">
									<div class="rs1-select2 bor8 bg0">
										<select class="js-select2" name="time">
											<option>Choose an option</option>
											<option>Kindle</option>
											<option>Audiobook</option>
											<option>Paperback</option>
											<option>Hardcover</option>
										</select>
										<div class="dropDownSelect2"></div>
									</div>
								</div>
							</div>

							<div class="flex-w flex-r-m p-b-10">
								<div class="size-204 flex-w flex-m respon6-next">
									<div class="wrap-num-product flex-w m-r-20 m-tb-10">
										<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-minus"></i>
										</div>

										<input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product" value="1">

										<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-plus"></i>
										</div>
									</div>

									<button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
										Add to cart
									</button>
								</div>
							</div>	
						</div>

							
							<div class="flex-w flex-m p-l-100 p-t-40 respon7">
								<div class="flex-m bor9 p-r-10 m-r-11">
									<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100" data-tooltip="Add to Wishlist">
										<i class="zmdi zmdi-favorite"></i>
									</a>
								</div>

								<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Facebook">
									<i class="fa fa-facebook"></i>
								</a>

								<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Twitter">
									<i class="fa fa-twitter"></i>
								</a>

								<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Google Plus">
									<i class="fa fa-google-plus"></i>
								</a>
							</div>

app/views/partials/_header.html.erb
	<!-- Header -->
	<header>
		<!-- Header desktop -->
		<div class="container-menu-desktop">
			<!-- Topbar -->
			<div class="top-bar">
				<div class="content-topbar flex-sb-m h-full container">
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>

					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m trans-04 p-lr-25">
							Help & FAQs
						</a>

						
					</div>
				</div>
			</div>

			<div class="wrap-menu-desktop">
				<nav class="limiter-menu-desktop container">
					
					<!-- Logo desktop -->		
					<a href="/home/index" class="logo">
					<h1 style="font-family: Yesteryear, cursive; color: gold;">BookShelf</h1>
					</a>

					<!-- Menu desktop -->
					<div class="menu-desktop">
						<ul class="main-menu" >
							<!--<li>
								<a href="/home/product" style="font-family: Yesteryear, cursive; color: gold; font-size: 30px">Catalog</a>
								<ul class="sub-menu">
									<li><a href="index.html">Homepage 1</a></li>
									<li><a href="home-02.html">Homepage 2</a></li>
									<li><a href="home-03.html">Homepage 3</a></li>
								</ul>
							</li>-->

							<li>
								<a href="/shops/index" style="font-family: Yesteryear, cursive; color: gold; font-size: 30px">Shop</a>
							</li>

							<li>
								<a href="/books" style="font-family: Yesteryear, cursive; color: gold; font-size: 30px">About</a>
							</li>

							<li class="label1" data-label1="hot">
								<a href="/home/stories" style="font-family: Yesteryear, cursive; color: gold; font-size: 30px">Stories</a>
							</li>

							<li>
								<a href="/home/contact" style="font-family: Yesteryear, cursive; color: gold; font-size: 30px">Contact</a>
							</li>
						</ul>
					</div>	

					<!-- Icon header -->
					<div class="wrap-icon-header flex-w flex-r-m">
						
						
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
							<i class="zmdi zmdi-search"></i>
						</div>
						
						
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="2">
							<i class="zmdi zmdi-shopping-cart"></i>
						</div>
						
						<a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="0">
							<i class="zmdi zmdi-favorite-outline"></i>
						</a>
						

						<% if user_signed_in? %>
						<% @AuthUser = current_user.username %>
						<% else %>
						<% @AuthUser = "Guest" %>
						<% end %>

						<li class="nav-item dropdown">
						<a class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11  nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="zmdi zmdi-account-circle" style="font: cursive; color: gold; font-size: 25px">&nbsp;<%= @AuthUser %></i>
						</a>
							<div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
								<% if user_signed_in? %>
								
								 <% if current_user.admin == true %>
								<a class="dropdown-item" <%= link_to 'Admin Controls', admin_index_path  %></a>
								<a class="dropdown-item"<%= link_to 'My Profile', home_profile_path %></a>
								<a class="dropdown-item" <%= link_to 'Profile Settings', edit_user_registration_path  %></a>
								<a class="dropdown-item" <%= link_to 'My Notes', posts_path  %></a>
								<a class="dropdown-item"<%= link_to 'Logout', destroy_user_session_path, method: :get %></a>
								
								<% else %>
								<a class="dropdown-item"<%= link_to 'My Profile', home_profile_path %></a>
								<a class="dropdown-item" <%= link_to 'Settings', edit_user_registration_path  %></a>
								<a class="dropdown-item" <%= link_to 'Posts', posts_path  %></a>
								<a class="dropdown-item"<%= link_to 'Logout', destroy_user_session_path, method: :get %></a>
								<% end %>
								<% else %>
								<a class="dropdown-item"<%= link_to 'Login', new_user_session_path %></a>
								<a class="dropdown-item" <%= link_to 'Sign Up', new_user_registration_path  %></a>
								<% end %>
        					</div>
						</li>
					</div>
					
				</nav>
			</div>	
		</div>




<!--End of Notice/Alert wrapper-->


		<!-- Header Mobile -->
		<div class="wrap-header-mobile">
			<!-- Logo moblie -->		
			<div class="logo-mobile">
				<a href="/home/index" class="logo">
				<h1 style="font-family: Yesteryear, cursive; color: gold;">BookShelf</h1>
				</a>
			</div>

			<!-- Icon header -->
			<div class="wrap-icon-header flex-w flex-r-m m-r-15">
				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
					<i class="zmdi zmdi-search"></i>
				</div>

				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify="2">
					<i class="zmdi zmdi-shopping-cart"></i>
				</div>

				<a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti" data-notify="0">
					<i class="zmdi zmdi-favorite-outline"></i>
				</a>
			</div>

			<!-- Button show menu -->
			<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</div>
		</div>


		<!-- Menu Mobile -->
		<div class="menu-mobile">
			<ul class="topbar-mobile">
				<li>
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>
				</li>

				<li>
					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m p-lr-10 trans-04">
							Help & FAQs
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							My Account
						</a>
					</div>
				</li>
			</ul>

			<ul class="main-menu-m">
				<li>
					<a href="/home/index">Home</a>
					<ul class="sub-menu-m">
						<li><a href="index.html">Homepage 1</a></li>
						<li><a href="home-02.html">Homepage 2</a></li>
						<li><a href="home-03.html">Homepage 3</a></li>
					</ul>
					<span class="arrow-main-menu-m">
						<i class="fa fa-angle-right" aria-hidden="true"></i>
					</span>
				</li>

				<li>
					<a href="/home/product">Shop</a>
				</li>

				<li>
					<a href="shoping-cart.html" class="label1 rs1" data-label1="hot">Features</a>
				</li>

				<li>
					<a href="blog.html">Blog</a>
				</li>

				<li>
					<a href="/books">About</a>
				</li>

				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>

		<!-- Modal Search -->
		<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
			<div class="container-search-header">
				<button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
                    <%= image_tag( "icons/icon-close2.png" ) %> 
				</button>

				<form class="wrap-search-header flex-w p-l-15">
					<button class="flex-c-m trans-04">
						<i class="zmdi zmdi-search"></i>
					</button>
					<input class="plh3" type="text" name="search" placeholder="Search...">
				</form>
			</div>
		</div>
	</header>

	<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="images/item-cart-01.jpg" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
                        
							<img src="images/item-cart-02.jpg" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="images/item-cart-03.jpg" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>

<!--Alert wrapper from https://codepen.io/CSWApps/pen/XJoLmN-->
<div class="alert alert-success" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

</div>



<style>
@import "compass/css3";

.alert{
  padding: 10px;
}

button.close {
    padding: 140;
    cursor: pointer;
    background: 0 0;
    border: 0;
}
</style>

<script>
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 4000);
</script>